### ISSUE TITLE
Please release a .uf2 file for the pico

### ISSUE THREAD

**Issue by wjhrdy** [synthead/timex-datalink-arduino#18]
To make using the pico easier you can release a uf2 file similar to this repo.

https://github.com/famiclone6502/DIY_Datalink_Adapter/tree/main/pico

which can be dragged to the device without compiling anything.

**Comment by synthead** [comment]
Oh interesting!  This is a neat idea!  I'm kinda hesitant to keep a compiled binary around as a tracked file, but I really like the idea of doing releases and adding binaries to the release.  The Teensy LC even has support for the same thing.  Maybe this could be integrated with GitHub actions?

**Comment by wjhrdy** [comment]
I agree that the Releases are the way to do it.

**Comment by synthead** [comment]
Created v1.0.0 and added both the RPi Pico uf2 and Teensy LC hex files to the release!

https://github.com/synthead/timex-datalink-arduino/releases/tag/v1.0.0

Thank you for the suggestion!
